apiVersion: v1
kind: Pod
metadata:
  name: curl-with-ambassador
spec:
  containers:
    - name: main
      image: curlimages/curl:8.5.0
      imagePullPolicy: IfNotPresent
      command: ["sleep", "9999999"]
    - name: ambassador
      image: luksa/kubectl-proxy:1.8.0
      imagePullPolicy: IfNotPresent
