apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
    - name: main
      image: curlimages/curl
      command: ["sleep", "9999999"]
    - name: dnsutils
      image: tutum/dnsutils
      command: ["sleep", "9999999"]
