---
apiVersion: v1
kind: Secret
metadata:
  name: adcm-ssl-certificate
type: Opaque
data:
  key.pem: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdDMvY2hzZ1NF
    WkZCaUJha3Z0ZTY5ZDY1TldCUDlWSFhKRGVBRHFhdmgvdGVDL2ZNCnppY0FNeXBZWHVESjQxR0Yx
    MnJ0c2VkUE1xOGYvOUpadllmT1J5dTFGTCtFWnYxYk1HVzM4ZE44UHh3bjlxRmcKdkJjMXk5cTYy
    VCtKL0JYeWplN0dhem1ZVnBFNFZFZHhFcjBWNDNQU1h6eHU5RGRjUUsrSGdNeTBhOHVRcnhUbApD
    dXFXZWNFWUhKZ08rWkR6NGgyWVBHU0tPQXBUaXJUVlNMNW1CWmZhT3FmMHhiUDk4NEhSUDkyRVps
    MktGYUNlCjM1V0tmYW9YQlZsY0V3dEtSU1g1QVoyS2lsRDhJdlRrZHMrU0o4Zk01S0JSRExRQ3dL
    WkJTU2tFbVl4dm10L1EKMG93ZDU2OE00WCtNeDFqbXArNTR5dDV1L2lDU1VMZHV5NXNZWVFJREFR
    QUJBb0lCQUFDSkpRY0NYOXNoUmhtMApSemd2YW1KUllNKzJha1ZZYWRKaDZjUEwyaDRCZzkxeEZH
    MzlwZE1yRlNXaHc3VWdNSGlDaUJNZTQ4Sk5kSlhMClNCWjA1bUNhMExxR0hKMkRCb01nL2pwOGd1
    a0VRZ2J4b3dDcGsxbjNBaTM1aGk1RmozY09uV2NFRWdmSlZoVnUKUFV4Rlg3ZW04ajd6bVl5bytn
    eWpvVGVsREFSM05iNGZpZDg4WGtSb2Fqb05vWWtaakdETzVib1pyZGwyb0w0NApHaDdGaEE0NDlM
    ekNMSjJOYzB0RU45NHVhL01rMnczSmQrbStwV3VmT1JXeWRxM29kYktPd2JLUzFybUNTeEZ3Ci9q
    YUJrZXJpU3V5K1JHOWNNOHZGT2dBQTFTUThUZWpQTnkrbTQwK0I0N2pEb2t5UWVrSVNpejJVRjY1
    bE5NYUgKLzI1RzJ1RUNnWUVBeWRSM3Q5QW9oUks2UVB4YjI2K2tlY1hHOXpBQ3VuNEJSS1BLV1FP
    ZzVoeHB5NFBKOHhqZQpPVlVxaU1hTFZ6bmFxQ3ZSejBGTnliU09INWY4aWp0ZXZhMHd1OVJISTk3
    TWUyRWt4a3ZIT1I4TEdRL2ZZRWhHCncyNE1RdTFxbTNrT0ZWek51WVREV3hzSkV5eE5OZHJXR1NH
    TWNBUDdXOW1DMWVBV2xYR0dBMDBDZ1lFQTZML3MKa2VFODcxeE5XWjhXWlNkNFUwYzdKMHVkcEVa
    VW1jOThVUzJFd1dBK25Pd1BBdTdCQXYyTFNOVE80UXRTYzFiUwp4OEJSeWowWlBLbTYzZFZDQ2VU
    MEFXc1BGdEZuTC9FQm83NkFNdmFkdlNZZEJjZ0lzS1F3SjRjNnBpTUUyVExBCjdSeWdPY3Z2UWZu
    WmdKVHkvQkIxcjJvZTc3UHVPM1FOdU45L2QyVUNnWUJTZGRSVDdXQWd2bjRLZnhDb3VTSmgKL2tS
    RVNnRlRZSmYwQzFkbzl1cU9HWjIvNEtCcUNnY0JOYUtqTHp0TzcvdytLV2tYWEg4RG9obFBIekcy
    NkhyVQoxQ1hORi9YWTJmYUJramNNTFhuQUJNYnIvbWd0VmxwVERtdEVET3c1aVVRUHhsTG5NUzcv
    MGhQckdYYVNRazZuCkJlWHkvaTE4WVducktCc1NBOGZWSVFLQmdCdWwyTXRIYno2YnYxQjdGbVR6
    dUZaa0tzR3pPTW12MVJMa1U4Y3MKMmcxQ2lvMkhlUTBISVlSaWErNDk0VWxZVi9YOWhWSlhKU0Fa
    KytwNTJ3bkk4R3hPZHpISDd1WHVBQXp3MnhvQgpZaWNycG5jMmxOSC8vaEJGb0xiQldKVXRxY0RI
    UjZXaTllR0h1U2NrTDlNWFhublUxclg4ckNvYlBKeHhYOFByClFMQUZBb0dCQUpBd05icVRaS2k2
    d1BNcm9xZW1XaDVsNGlrdFNlSjhxMG9RNU4zb1AwMCt5WVJEYU9BYWE5N3cKMVc5L1BEbys3VVh3
    QlgvSFV5ai9HbER4SEhJUjRPQThTakpXNFZZWFVnWVRDWGJUanRHNDdmTmRYNjlLbzBIcgoxMjZN
    VTBMRWw1ZjViRVhDL1RTakQxOWdCRnVQWHI2WlFIMERKWncwV3Y0TmVsTy9KNE42Ci0tLS0tRU5E
    IFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  cert.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2VENDQTlHZ0F3SUJBZ0lTQTBuRTF0NmxD
    OFFqZ1NFVG0yZmZqWkdDTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRN
    Ull3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlN
    ekV3TURZd09URXlOVFJhRncweU5EQXhNRFF3T1RFeU5UTmFNQmt4RnpBVkJnTlZCQU1UCkRuTnVi
    M0I0TG1Sa2JuTXVibVYwTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FR
    RUEKdDMvY2hzZ1NFWkZCaUJha3Z0ZTY5ZDY1TldCUDlWSFhKRGVBRHFhdmgvdGVDL2ZNemljQU15
    cFlYdURKNDFHRgoxMnJ0c2VkUE1xOGYvOUpadllmT1J5dTFGTCtFWnYxYk1HVzM4ZE44UHh3bjlx
    Rmd2QmMxeTlxNjJUK0ovQlh5CmplN0dhem1ZVnBFNFZFZHhFcjBWNDNQU1h6eHU5RGRjUUsrSGdN
    eTBhOHVRcnhUbEN1cVdlY0VZSEpnTytaRHoKNGgyWVBHU0tPQXBUaXJUVlNMNW1CWmZhT3FmMHhi
    UDk4NEhSUDkyRVpsMktGYUNlMzVXS2Zhb1hCVmxjRXd0SwpSU1g1QVoyS2lsRDhJdlRrZHMrU0o4
    Zk01S0JSRExRQ3dLWkJTU2tFbVl4dm10L1Ewb3dkNTY4TTRYK014MWptCnArNTR5dDV1L2lDU1VM
    ZHV5NXNZWVFJREFRQUJvNElDRURDQ0Fnd3dEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CMEcKQTFVZEpR
    UVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFV
    ZApEZ1FXQkJRK3hudHRmWFJyaFcwdW4xUC9ERWQweFlrSkR6QWZCZ05WSFNNRUdEQVdnQlFVTHJN
    WHQxaFd5NjVRCkNVRG1INitkaXhUQ3hqQlZCZ2dyQmdFRkJRY0JBUVJKTUVjd0lRWUlLd1lCQlFV
    SE1BR0dGV2gwZEhBNkx5OXkKTXk1dkxteGxibU55TG05eVp6QWlCZ2dyQmdFRkJRY3dBb1lXYUhS
    MGNEb3ZMM0l6TG1rdWJHVnVZM0l1YjNKbgpMekFaQmdOVkhSRUVFakFRZ2c1emJtOXdlQzVrWkc1
    ekxtNWxkREFUQmdOVkhTQUVEREFLTUFnR0JtZUJEQUVDCkFUQ0NBUVFHQ2lzR0FRUUIxbmtDQkFJ
    RWdmVUVnZklBOEFCMkFOcTJ2MnMvdGJZaW41dkN1MXhyNkhDUmNXeTcKVVlTRk5MMmtQVEJJMS91
    ckFBQUJpd1I1MGpVQUFBUURBRWN3UlFJaEFMTHB3clhXMm9XTjVPcjFOdEsyd0hrMQpSbEZEYndN
    cmV5L2xPcURVUTA3TEFpQXJPTUk0enZDVnYyNWpDSFBNQ1VrQ1M5bWt2eG9kMzRSRkc5RXZ1S0hZ
    Cnh3QjJBTzdOMEdUVjJ4ck94VnkzbmJUTkU2SXloMFo4dk96ZXcxRklXVVp4SDdXYkFBQUJpd1I1
    MGg4QUFBUUQKQUVjd1JRSWhBSU41VUZaNGhOMHFWVWJiWFhTVWFvMUNCVFFsVVVRbEVseng4UGZF
    Z3VYUEFpQVhYQlh4OFFmYwpnWWxFN2svQU83ZWJYeXhjSUUrdTJkVXNJK0ZsbCtHOEpEQU5CZ2tx
    aGtpRzl3MEJBUXNGQUFPQ0FRRUFmUWNNCjFjVDNJejNGSXdabm5ScGlJWi8vU2xPWXVkSTMzTkVk
    eHJvK2R0dGlyamVXaXQxTmR3NTFETFgyRGlpWG1wUkEKZWloZzN0OXQ2M1BNSkZVT20rbDVCNHVN
    bjFBbVVyT3AwMy9RRldRZEcwS1ZJYTZjRHVISWIvZDM1bTE1aUNsVApOSjNRemtUM2htSzMrOEcz
    MjE4aUlMTVRYRnRTdmZnTWFBSDlGUVgyUlI2SC9BR2wwYm9jNC9hY0d0TXRXTm5OCklpN1NoaVlu
    SnZVOGNSODhCaURxWmh1KzNTVE5aQ1lMUXJPZTJJYm50Zkl5Z01oa1MwTW8xYm41dm5zcUh2WG0K
    RS9MWUJCWDAraG5sVE0zK2xaekhsZElWVkQyRjlMMi9mSGpIdFdOdmk3NXFGN3hyU2RqSUdseXZM
    WmFZTkN0egovekI0YVFDK0h4R2wwUWlac2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0t
    LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlGRmpDQ0F2NmdBd0lCQWdJUkFKRXJDRXJQREJp
    blUvYldMaVduWDFvd0RRWUpLb1pJaHZjTkFRRUxCUUF3ClR6RUxNQWtHQTFVRUJoTUNWVk14S1RB
    bkJnTlZCQW9USUVsdWRHVnlibVYwSUZObFkzVnlhWFI1SUZKbGMyVmgKY21Ob0lFZHliM1Z3TVJV
    d0V3WURWUVFERXd4SlUxSkhJRkp2YjNRZ1dERXdIaGNOTWpBd09UQTBNREF3TURBdwpXaGNOTWpV
    d09URTFNVFl3TURBd1dqQXlNUXN3Q1FZRFZRUUdFd0pWVXpFV01CUUdBMVVFQ2hNTlRHVjBKM01n
    ClJXNWpjbmx3ZERFTE1Ba0dBMVVFQXhNQ1VqTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElC
    RHdBd2dnRUsKQW9JQkFRQzdBaFVvelBhZ2xOTVBFdXlOVlpMRCtJTHhtYVo2UW9pblhTYXF0U3U1
    eFV5eHI0NXIrWFhJbzljUApSNVFVVlRWWGpKNm9vamtaOVlJOFFxbE9idlU3d3k3YmpjQ3dYUE5a
    T09mdHoybndXZ3NidnNDVUpDV0gramR4CnN4UG5IS3pobSsvYjVEdEZVa1dXcWNGVHpqVElVdTYx
    cnUyUDNtQnc0cVZVcTdadERwZWxRRFJySzlPOFp1dG0KTkh6NmE0dVBWeW1aK0RBWFhicHliL3VC
    eGEzU2hsZzlGOGZuQ2J2eEsvZUczTUhhY1YzVVJ1UE1yU1hCaUx4ZwpaM1Ztcy9FWTk2SmM1bFAv
    T29pMlI2WC9FeGpxbUFsM1A1MVQrYzhCNWZXbWNCY1VyMk9rLzVtems1M2NVNmNHCi9raUZIYUZw
    cmlWMXV4UE1VZ1AxN1ZHaGk5c1ZBZ01CQUFHamdnRUlNSUlCQkRBT0JnTlZIUThCQWY4RUJBTUMK
    QVlZd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3SUdDQ3NHQVFVRkJ3TUJNQklHQTFVZEV3RUIv
    d1FJTUFZQgpBZjhDQVFBd0hRWURWUjBPQkJZRUZCUXVzeGUzV0ZiTHJsQUpRT1lmcjUyTEZNTEdN
    QjhHQTFVZEl3UVlNQmFBCkZIbTBXZVo3dHVYa0FYT0FDSWpJR2xqMjZadHVNRElHQ0NzR0FRVUZC
    d0VCQkNZd0pEQWlCZ2dyQmdFRkJRY3cKQW9ZV2FIUjBjRG92TDNneExta3ViR1Z1WTNJdWIzSm5M
    ekFuQmdOVkhSOEVJREFlTUJ5Z0dxQVloaFpvZEhSdwpPaTh2ZURFdVl5NXNaVzVqY2k1dmNtY3ZN
    Q0lHQTFVZElBUWJNQmt3Q0FZR1o0RU1BUUlCTUEwR0N5c0dBUVFCCmd0OFRBUUVCTUEwR0NTcUdT
    SWIzRFFFQkN3VUFBNElDQVFDRnlrNUhQcVAzaFVTRnZOVm5lTEtZWTYxMVRSNlcKUFRObGNsUXRn
    YURxdyszNElMOWZ6TGR3QUxkdU8vWmVsTjdrSUorbTc0dXlBK2VpdFJZOGtjNjA3VGtDNTN3bApp
    a2ZtWlc0L1J2VFo4TTZVSys1VXpoSzhqQ2RMdU1HWUw2S3Z6WEdSU2dpM3lMZ2pld1F0Q1BrSVZ6
    NkQyUVF6CkNrY2hlQW1DSjhNcXlKdTV6bHp5Wk1qQXZubkFUNDV0UkF4ZWtyc3U5NHNRNGVnZFJD
    bmJXU0R0WTdraCtCSW0KbEpOWG9CMWxCTUVLSXE0UURVT1hvUmdmZnVEZ2hqZTFXckc5TUwrSGJp
    c3EveUZPR3dYRDlSaVg4RjZzdzZXNAphdkF1dkRzenVlNUwzc3o4NUsrRUM0WS93RlZETnZabzRU
    WVhhbzZaMGYrbFFLYzB0OERRWXprMU9YVnU4cnAyCnlKTUM2YWxMYkJmT0RBTFp2WUg3bjdkbzFB
    WmxzNEk5ZDFQNGpua0RyUW94QjNVcVE5aFZsM0xFS1E3M3hGMU8KeUs1R2hERFg4b1ZmR0tGNXUr
    ZGVjSXNINFlhVHc3bVAzR0Z4SlNxdjMrMGxVRkpvaTVMYzVkYTE0OXA5MElkcwpoQ0V4cm9MMSs3
    bXJ5SWtYUGVGTTVUZ085cjBydlphQkZPdlYyejBncDM1WjArTDRXUGxidUVqTi9seFBGaW4rCkhs
    VWpyOGdSc0kzcWZKT1FGeS85cktJSlIwWS84T213dC84b1RXZ3kxbWRlSG1tams3ajFuWXN2QzlK
    U1E2WnYKTWxkbFRUS0IzemhUaFYxK1hXWXA2cmpkNUpXMXpiVldFa0xOeEU3R0pUaEVVRzNzemdC
    VkdQN3BTV1RVVHNxWApuTFJid0hPb3E3aEh3Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZZRENDQkVpZ0F3SUJBZ0lRUUFGM0lUZlU2
    VUs0N25hcVBHUUt0ekFOQmdrcWhraUc5dzBCQVFzRkFEQS8KTVNRd0lnWURWUVFLRXh0RWFXZHBk
    R0ZzSUZOcFoyNWhkSFZ5WlNCVWNuVnpkQ0JEYnk0eEZ6QVZCZ05WQkFNVApEa1JUVkNCU2IyOTBJ
    RU5CSUZnek1CNFhEVEl4TURFeU1ERTVNVFF3TTFvWERUSTBNRGt6TURFNE1UUXdNMW93ClR6RUxN
    QWtHQTFVRUJoTUNWVk14S1RBbkJnTlZCQW9USUVsdWRHVnlibVYwSUZObFkzVnlhWFI1SUZKbGMy
    VmgKY21Ob0lFZHliM1Z3TVJVd0V3WURWUVFERXd4SlUxSkhJRkp2YjNRZ1dERXdnZ0lpTUEwR0NT
    cUdTSWIzRFFFQgpBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRQ3Q2Q1J6OUJRMzg1dWVLMWNvSEllKzNM
    ZmZPSkNNYmp6bVY2QjQ5M1hDCm92NzFhbTcyQUU4bzI5NW9obXhFazdheFkvMFVFbXUvSDlMcU1a
    c2hmdEV6UExwSTlkMTUzN080L3hMeElacEwKd1lxR2NXbEtabVpzajM0OGNMK3RLU0lHOCtUQTVv
    Q3U0a3VQdDVsK2xBT2YwMGVYZkpsSUkxUG9PSzVQQ20rRApMdEZKVjR5QWRMYmFMOUE0alhzRGND
    RWJkZkl3UFBxUHJ0M2FZNnZyRmsvQ2poRkxmczhMNlArMWR5NzBzbnRLCjRFd1NKUXh3alFNcG9P
    RlRKT3dUMmU0WnZ4Q3pTb3cvaWFOaFVkNnNod2VVOUdOeDdDN2liMXVZZ2VHSlhEUjUKYkhidk81
    QmllZWJicEpvdkpzWFFFT0VPM3RrUWpoYjd0L2VvOThmbEFnZVlqellJbGVmaU41WU5ObldlK3c1
    eQpzUjJidkFQNVNRWFlnZDBGdENyV1FlbXNBWGFWQ2cvWTM5VzlFaDgxTHlnWGJOS1l3YWdKWkhk
    dVJ6ZTZ6cXhaClhtaWRmM0xXaWNVR1FTaytXVDdkSnZVa3lSR25XcU5NUUI5R29abTFwenBSYm9Z
    N25uMXlweElGZUZudFBsRjQKRlFzRGo0M1FMd1d5UG50S0hFdHpCUkw4eHVyZ1VCTjhRNU4wczhw
    MDU0NGZBUWpRTU5SYmNUYTBCN3JCTURCYwpTTGVDTzVpbWZXQ0tvcU1wZ3N5NnZZTUVHNktEQTBH
    aDFnWHhHOEsyOEtoOGhqdEdxRWdxaU54Mm1uYS9IMnFsClBSbVA2emp6Wk43SUt3MEtLUC8zMitJ
    VlF0UWkwQ2RkNFhuK0dPZHdpSzFPNXRtTE9zYmRKMUZ1Lzd4azlUTkQKVHdJREFRQUJvNElCUmpD
    Q0FVSXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQVFZdwpTd1lJS3dZ
    QkJRVUhBUUVFUHpBOU1Ec0dDQ3NHQVFVRkJ6QUNoaTlvZEhSd09pOHZZWEJ3Y3k1cFpHVnVkSEox
    CmMzUXVZMjl0TDNKdmIzUnpMMlJ6ZEhKdmIzUmpZWGd6TG5BM1l6QWZCZ05WSFNNRUdEQVdnQlRF
    cDdHa2V5eHgKK3R2aFM1QjEvOFFWWUlXSkVEQlVCZ05WSFNBRVRUQkxNQWdHQm1lQkRBRUNBVEEv
    QmdzckJnRUVBWUxmRXdFQgpBVEF3TUM0R0NDc0dBUVVGQndJQkZpSm9kSFJ3T2k4dlkzQnpMbkp2
    YjNRdGVERXViR1YwYzJWdVkzSjVjSFF1CmIzSm5NRHdHQTFVZEh3UTFNRE13TWFBdm9DMkdLMmgw
    ZEhBNkx5OWpjbXd1YVdSbGJuUnlkWE4wTG1OdmJTOUUKVTFSU1QwOVVRMEZZTTBOU1RDNWpjbXd3
    SFFZRFZSME9CQllFRkhtMFdlWjd0dVhrQVhPQUNJaklHbGoyNlp0dQpNQTBHQ1NxR1NJYjNEUUVC
    Q3dVQUE0SUJBUUFLY3dCc2xtNy9EbExRcnQyTTUxb0dyUytvNDQrL3lRb0RGVkRDCjVXeEN1Miti
    OUxSUHdrU0lDSFhNNndlYkZHSnVlTjdzSjdvNVhQV2lvVzVXbEhBUVU3Rzc1Sy9Rb3NNckFkU1cK
    OU1VZ05UUDUyR0UyNEhHTnRMaTFxb0pGbGNEeXFTTW81OWFoeTJjSTJxQkRMS29ia3gvSjN2V3Jh
    VjBUOVZ1RwpXQ0xLVFZYa2NHZHR3bGZGUmpsQno0cFlnMWh0bWY1WDZEWU84QTRqcXYySWw5RGpY
    QTZVU2JXMUZ6WFNMcjlPCmhlOFk0SVdTNndZN2JDa2pDV0RjUlFKTUVoZzc2ZnNPM3R4RStGaVly
    dXE5UlVXaGlGMW15djRRNlcrQ3lCRkMKRGZ2cDdPT0dBTjZkRU9NNCtxUjlzZGpvU1lLRUJwc3I2
    R3RQQVF3NGR5NzUzZWM1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  POSTGRES_USER: adcm_user
  POSTGRES_PASSWORD: adcm_password
  POSTGRES_DB: adcm_db
  POSTGRES_TCP_PORT: "5432"

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: postgres:15.2
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: pg-data
          hostPath:
            path: /home/k8s_volumes/pg_data

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: adcm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adcm
  template:
    metadata:
      labels:
        app: adcm
    spec:
      automountServiceAccountToken: false
      containers:
        - name: adcm
          image: arenadata/adcm:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_TCP_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: ssl-certs
              mountPath: /adcm/data/conf/ssl
              readOnly: true
            - name: adcm-data
              mountPath: /adcm/data
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: adcm-data
          hostPath:
            path: /home/k8s_volumes/adcm-data
        - name: ssl-certs
          secret:
            secretName: adcm-ssl-certificate

---
apiVersion: v1
kind: Service
metadata:
  name: adcm-service-http #Change with Ingress
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
  selector:
    app: adcm

---
apiVersion: v1
kind: Service
metadata:
  name: adcm-service-https #Change with Ingress
spec:
  type: NodePort
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30443
  selector:
    app: adcm
