apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: cr.yandex/crpv4vat29nq8ri5so6o/kubia:latest
        ports:
        - containerPort: 8080
