apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
    - image: cr.yandex/crpv4vat29nq8ri5so6o/kubia:latest
      name: kubia
      ports:
      - containerPort: 8080
        protocol: TCP
